#!/bin/bash

export CUDA_VISIBLE_DEVICES=0

python src/train_kbnet.py \
--train_image_path training/kitti/kitti_train_image-clean.txt \
--train_sparse_depth_path training/kitti/kitti_train_sparse_depth-clean.txt \
--train_intrinsics_path training/kitti/kitti_train_intrinsics-clean.txt \
--val_image_path validation/kitti/kitti_val_image.txt \
--val_sparse_depth_path validation/kitti/kitti_val_sparse_depth.txt \
--val_intrinsics_path validation/kitti/kitti_val_intrinsics.txt \
--val_ground_truth_path validation/kitti/kitti_val_ground_truth.txt \
--n_batch 8 \
--n_height 320 \
--n_width 768 \
--input_channels_image 3 \
--input_channels_depth 2 \
--normalized_image_range 0 1 \
--outlier_removal_kernel_size 7 \
--outlier_removal_threshold 1.5 \
--min_pool_sizes_sparse_to_dense_pool 5 7 9 11 13 \
--max_pool_sizes_sparse_to_dense_pool 15 17 \
--n_convolution_sparse_to_dense_pool 3  \
--n_filter_sparse_to_dense_pool 8 \
--n_filters_encoder_image 48 96 192 384 384 \
--n_filters_encoder_depth 16 32 64 128 128 \
--resolutions_backprojection 0 1 2 3 \
--n_filters_decoder 256 128 128 64 12 \
--deconv_type up \
--min_predict_depth 1.5 \
--max_predict_depth 100.0 \
--weight_initializer xavier_normal \
--activation_func leaky_relu \
--learning_rates 5e-5 1e-4 15e-5 1e-4 5e-5 2e-5  \
--learning_schedule 2 8 20 30 45 60 \
--augmentation_probabilities 1.00 0.50 0.25 \
--augmentation_schedule 50 55 60 \
--augmentation_random_crop_type horizontal vertical anchored bottom \
--augmentation_random_remove_points 0.60 0.70 \
--augmentation_random_noise_type none \
--augmentation_random_noise_spread -1 \
--w_color 0.15 \
--w_structure 0.95 \
--w_sparse_depth 0.60 \
--w_smoothness 0.0400 \
--w_weight_decay_depth 0.00 \
--w_weight_decay_pose 0.00 \
--min_evaluate_depth 0.0 \
--max_evaluate_depth 100.0 \
--n_summary 5000 \
--n_checkpoint 5000 \
--validation_start 300000 \
--checkpoint_path trained_kbnet/kitti/kbnet_model \
--device gpu \
--n_thread 8
